import { Router } from "express";
import ProductCateogry from "../controllers/productController.js";
import auth from "../middlewares/authHandler.js";
import upload_config from "../services/uploadHandler.js";
const productRouter = Router();
productRouter.post('/addcategory',auth,ProductCateogry.addCategory);
productRouter.get('/categorylist',ProductCateogry.categoryList);
productRouter.get('/categorydetails/:ID',ProductCateogry.categoryDetail);
productRouter.put('/categoryupdate/:ID',auth,ProductCateogry.categoryUpdate);
productRouter.delete('/categorydelete/:ID',auth,ProductCateogry.categoryDelete);
productRouter.post('/addproduct',auth,upload_config.single('image'),ProductCateogry.addProduct);
productRouter.get('/productlist',ProductCateogry.productList);
productRouter.get('/productdetails/:ID',ProductCateogry.productDetails);
productRouter.get('/productdetailsbycategory/:ID',ProductCateogry.productDetailsByCategry);
productRouter.get('/productdetailsbyprice',ProductCateogry.productDetailsByPrice);
productRouter.delete('/productdelete/:ID',auth,ProductCateogry.productDelete);
productRouter.put('/productupdate/:ID',auth,upload_config.single('image'),ProductCateogry.productUpdate);
productRouter.put('/productuploadbyid/:ID',auth,upload_config.single('image'),ProductCateogry.productImageUploadById);
export default productRouter;
